type TextFn = (childName: string, house: number, adjSuffix: string) => string;

export const PLANET_INTERPRETATIONS: Record<string, Record<string, TextFn>> = {
  Sol: {
    Aries: (n, h) => `Con el Sol en Aries en la casa ${h}, ${n} nació con una energía pionera que lo impulsa a actuar antes que nadie. Su esencia más profunda es la del iniciador valiente que abre caminos nuevos con entusiasmo y determinación. En la casa ${h} esta energía solar se expresa con intensidad especial. Acompañarle significa respetar su necesidad de acción y liderazgo natural.`,
    Tauro: (n, h) => `Con el Sol en Tauro en la casa ${h}, ${n} llegó al mundo con una energía profunda, paciente y conectada con lo tangible. Su esencia más verdadera está en crear belleza, construir cosas duraderas y disfrutar los placeres simples de la vida. En la casa ${h} esta determinación silenciosa pero irresistible se expresa con más fuerza. ${n} necesita entornos estables y rutinas que le ofrezcan seguridad para florecer.`,
    Géminis: (n, h) => `Con el Sol en Géminis en la casa ${h}, ${n} nació con una mente brillante, veloz y perpetuamente curiosa. Su esencia más profunda es la del comunicador nato que conecta ideas y personas con igual facilidad. La casa ${h} marca el área donde esta curiosidad se vuelve más intensa y valiosa. ${n} aprenderá y crecerá mejor en ambientes que estimulen su mente y le ofrezcan variedad constante.`,
    Cáncer: (n, h) => `Con el Sol en Cáncer en la casa ${h}, ${n} llegó al mundo con un corazón profundamente intuitivo y una capacidad de nutrir que sorprende desde pequeño. Su esencia más verdadera está en crear vínculos emocionales auténticos y profundos. En la casa ${h} esta energía lunar se expresa con especial sensibilidad. ${n} necesita sentirse amado y seguro para mostrar todo su potencial.`,
    Leo: (n, h) => `Con el Sol en Leo en la casa ${h}, ${n} nació con un brillo interior que ilumina cualquier espacio que habita. Su esencia más profunda es la del creador generoso que da amor con el corazón abierto. La casa ${h} es el escenario donde este sol brilla con más intensidad. ${n} necesita reconocimiento genuino y oportunidades para expresar su creatividad sin límites.`,
    Virgo: (n, h) => `Con el Sol en Virgo en la casa ${h}, ${n} llegó al mundo con un don extraordinario para el análisis, el detalle y el servicio. Su esencia más verdadera está en mejorar lo que toca con maestría y dedicación. En la casa ${h} esta energía perfeccionista se aplica con profundidad. ${n} encontrará su mayor satisfacción cuando puede ayudar de manera concreta y ver resultados tangibles.`,
    Libra: (n, h) => `Con el Sol en Libra en la casa ${h}, ${n} nació con una sensibilidad estética y un sentido de justicia extraordinarios. Su esencia más profunda es la del armonizador que busca equilibrio en todas sus relaciones. La casa ${h} marca el área donde esta búsqueda de equilibrio es más significativa. ${n} necesita entornos armoniosos y justos para desarrollar todo su potencial.`,
    Escorpio: (n, h) => `Con el Sol en Escorpio en la casa ${h}, ${n} llegó al mundo con una profundidad emocional y una intensidad que poca gente puede igualar. Su esencia más verdadera está en transformar lo que toca y revelar verdades ocultas. La casa ${h} es el área donde esta energía transformadora actúa con más fuerza. ${n} necesita que confíen en su profundidad y no le pidan que sea superficial.`,
    Sagitario: (n, h) => `Con el Sol en Sagitario en la casa ${h}, ${n} nació con un espíritu aventurero y una búsqueda constante de significado. Su esencia más profunda es la del filósofo viajero que expande horizontes y comparte sabiduría. En la casa ${h} esta energía expansiva encuentra su mayor expresión. ${n} necesita libertad, aventura y espacios para hacer preguntas grandes sobre la vida.`,
    Capricornio: (n, h) => `Con el Sol en Capricornio en la casa ${h}, ${n} llegó al mundo con una madurez y determinación que superan su edad. Su esencia más verdadera está en construir, lograr y dejar un legado duradero. La casa ${h} marca el área donde esta ambición se vuelve más evidente. ${n} necesita metas claras y reconocimiento de sus logros.`,
    Acuario: (n, h) => `Con el Sol en Acuario en la casa ${h}, ${n} llegó al mundo con ideas que trascienden su tiempo y una misión de innovar para el bien de todos. Su esencia más profunda es la del visionario humanitario que piensa diferente y no tiene miedo de serlo. En la casa ${h} esta originalidad se expresa con mayor libertad. ${n} necesita espacio para ser único, sin presión para encajar en moldes que no son para él.`,
    Piscis: (n, h) => `Con el Sol en Piscis en la casa ${h}, ${n} llegó al mundo con una sensibilidad espiritual y una compasión que tocan el alma de quienes le rodean. Su esencia más verdadera está en disolver fronteras entre el mundo visible y el invisible. La casa ${h} es el área donde esta energía mística se expresa con más intensidad. ${n} necesita tiempo en silencio, contacto con el arte y ambientes amorosos que respeten su naturaleza soñadora.`,
  },
  Luna: {
    Aries: (n, h) => `Con la Luna en Aries en la casa ${h}, ${n} procesa sus emociones de manera rápida, intensa y directa. Sus sentimientos son como chispas: aparecen con fuerza y se transforman con igual rapidez. En la casa ${h} esta Luna impulsiva busca acción como vía de regulación emocional. ${n} necesita que sus emociones sean validadas sin demora y que se le ofrezcan salidas físicas para procesar lo que siente.`,
    Tauro: (n, h) => `Con la Luna en Tauro en la casa ${h}, ${n} encuentra su seguridad emocional en la constancia, el contacto físico y los entornos predecibles. Sus emociones son profundas como raíces: lentas en moverse pero extremadamente sólidas. La casa ${h} indica el área donde esta necesidad de estabilidad es más importante. ${n} se regula emocionalmente a través de texturas, música y la presencia calmante de sus personas de confianza.`,
    Géminis: (n, h) => `Con la Luna en Géminis en la casa ${h}, ${n} procesa sus emociones a través de las palabras y el movimiento mental. Hablar, escribir o jugar con ideas es la manera en que digiere lo que siente. La casa ${h} señala el área donde esta mente emocional es más activa. ${n} necesita que sus sentimientos sean escuchados con paciencia y que se le ayude a poner nombre a sus estados internos.`,
    Cáncer: (n, h) => `Con la Luna en Cáncer en la casa ${h}, ${n} tiene un mundo emocional extraordinariamente rico y profundo. Es un niño altamente intuitivo que siente el ambiente familiar con toda su piel. La casa ${h} marca el área donde esta sensibilidad lunar es más intensa. ${n} necesita rituales de seguridad, mucho contacto físico y saber sin duda que es amado para florecer plenamente.`,
    Leo: (n, h) => `Con la Luna en Leo en la casa ${h}, ${n} necesita reconocimiento, afecto expresivo y oportunidades para brillar para regular su mundo emocional. Sus emociones son dramáticas y cálidas, como el fuego: visibles, generosas y necesitadas de atención. La casa ${h} es el escenario donde esta Luna busca su audiencia. Decirle que lo amas con palabras claras y celebrar sus logros alimenta su corazón de manera profunda.`,
    Virgo: (n, h) => `Con la Luna en Virgo en la casa ${h}, ${n} procesa sus emociones a través del análisis y las rutinas. Encontrará calma en saber qué viene después, en tener roles claros y en poder ayudar de manera concreta. La casa ${h} indica el área donde esta necesidad de orden emocional es más visible. ${n} se regula mejor con horarios predecibles y conversaciones que le ayuden a entender el "por qué" de lo que siente.`,
    Libra: (n, h) => `Con la Luna en Libra en la casa ${h}, ${n} busca armonía emocional en todas sus relaciones. Las discusiones y los conflictos le afectan profundamente, y necesita entornos donde reine la paz y la justicia. La casa ${h} señala el área donde esta necesidad de equilibrio emocional es más evidente. ${n} florece cuando siente que hay equidad a su alrededor.`,
    Escorpio: (n, h) => `Con la Luna en Escorpio en la casa ${h}, ${n} tiene emociones de una profundidad y una intensidad poco comunes. Puede parecer reservado, pero su vida emocional interior es vastísima. La casa ${h} marca el área donde esta intensidad lunar es más activa. ${n} necesita que su mundo emocional sea respetado sin presionarle a abrirse antes de estar listo, y que sus cuidadores sean personas de absoluta confianza.`,
    Sagitario: (n, h) => `Con la Luna en Sagitario en la casa ${h}, ${n} tiene emociones expansivas, optimistas y ligadas a la búsqueda de aventura y significado. Se regula emocionalmente cuando tiene libertad para explorar, moverse y hacer preguntas filosóficas. La casa ${h} indica el área donde esta Luna aventurera busca su espacio. ${n} necesita que no se le sofoque con demasiadas reglas.`,
    Capricornio: (n, h) => `Con la Luna en Capricornio en la casa ${h}, ${n} gestiona sus emociones con una madurez sorprendente para su edad. Puede parecer estoico o poco expresivo, pero su vida interior es profunda y seria. La casa ${h} señala el área donde esta Luna práctica es más activa. ${n} necesita que se reconozca su esfuerzo y que las expectativas sean claras.`,
    Acuario: (n, h) => `Con la Luna en Acuario en la casa ${h}, ${n} procesa sus emociones desde una perspectiva lógica e independiente. Necesita su espacio para sentirse bien y puede disfrutar más de la conexión en grupos que en el uno a uno. La casa ${h} indica el área donde esta Luna independiente es más activa. ${n} florece cuando se le respeta su individualidad y se le permite conectar con sus pares de maneras originales.`,
    Piscis: (n, h) => `Con la Luna en Piscis en la casa ${h}, ${n} es extremadamente sensible al ambiente emocional que le rodea. Absorbe los estados de ánimo ajenos como una esponja y necesita entornos tranquilos para no sentirse abrumado. La casa ${h} marca el área donde esta Luna soñadora es más receptiva. ${n} se regula emocionalmente con música, arte, agua y el contacto con la naturaleza.`,
  },
  Mercurio: {
    Aries: (n, h) => `Con Mercurio en Aries en la casa ${h}, ${n} tiene una mente rápida, directa y que va al grano sin rodeos. Aprende mejor a través de la acción y los desafíos que le exigen respuestas rápidas. La casa ${h} señala el área donde esta mente impulsiva se expresa con más fuerza. ${n} necesita estimulación intelectual constante y libertad para expresar sus ideas sin filtros.`,
    Tauro: (n, h) => `Con Mercurio en Tauro en la casa ${h}, ${n} piensa de manera lenta, deliberada y profundamente práctica. No le gustan las prisas mentales: necesita tiempo para procesar y llegar a sus propias conclusiones. La casa ${h} indica el área donde este pensamiento paciente se aplica con mayor profundidad. ${n} aprende mejor con materiales concretos y ejemplos del mundo real.`,
    Géminis: (n, h) => `Con Mercurio en Géminis en la casa ${h}, ${n} tiene una de las mentes más ágiles y multifacéticas del zodíaco. Puede procesar múltiples ideas simultáneamente y comunicarlas con una fluidez natural. La casa ${h} es donde esta mente brillante encuentra su mayor campo de juego. ${n} aprende más rápido cuando la información viene en formatos variados.`,
    Cáncer: (n, h) => `Con Mercurio en Cáncer en la casa ${h}, ${n} piensa desde las emociones y tiene una memoria extraordinaria para todo lo que ha sentido. Su mente es intuitiva, imaginativa y profundamente conectada con el mundo interior. La casa ${h} señala el área donde este pensamiento emocional es más activo. ${n} aprende mejor en ambientes seguros y cálidos donde sus sentimientos son bienvenidos.`,
    Leo: (n, h) => `Con Mercurio en Leo en la casa ${h}, ${n} piensa de manera creativa, dramática y centrada en la expresión personal. Le encanta contar historias y comunicar sus ideas de maneras que capturen la atención. La casa ${h} indica el área donde este pensamiento brillante se expresa con mayor orgullo. ${n} aprende mejor cuando puede ser protagonista del proceso.`,
    Virgo: (n, h) => `Con Mercurio en Virgo en la casa ${h}, ${n} tiene una mente analítica, detallista y extraordinariamente precisa. Nota los errores que otros pasan por alto y tiene una capacidad natural para organizar información compleja. La casa ${h} señala el área donde este pensamiento meticuloso es más valioso. ${n} aprende mejor con información organizada y la oportunidad de revisar su trabajo.`,
    Libra: (n, h) => `Con Mercurio en Libra en la casa ${h}, ${n} tiene una mente diplomática que siempre busca ver todos los lados de una situación antes de decidir. Es un pensador justo con una comunicación naturalmente elegante. La casa ${h} indica el área donde este pensamiento equilibrado aporta más valor. ${n} aprende mejor en ambientes donde se debate de manera respetuosa.`,
    Escorpio: (n, h) => `Con Mercurio en Escorpio en la casa ${h}, ${n} tiene una mente penetrante que va siempre más allá de la superficie. Sus preguntas son profundas, su pensamiento es estratégico y su intuición intelectual es extraordinaria. La casa ${h} señala el área donde esta mente investigadora es más activa. ${n} aprende mejor cuando puede profundizar en los temas que le apasionan.`,
    Sagitario: (n, h) => `Con Mercurio en Sagitario en la casa ${h}, ${n} tiene una mente filosófica que siempre busca el panorama completo y el sentido más profundo. Aprende mejor cuando puede conectar lo que estudia con algo significativo para su vida. La casa ${h} indica el área donde esta mente expansiva encuentra más inspiración. ${n} necesita libertad para hacer preguntas grandes.`,
    Capricornio: (n, h) => `Con Mercurio en Capricornio en la casa ${h}, ${n} piensa de manera estructurada, estratégica y orientada a resultados concretos. Su mente es seria, práctica y tiene una capacidad notable para la planificación a largo plazo. La casa ${h} señala el área donde este pensamiento organizado aporta más fortaleza. ${n} aprende mejor con objetivos claros y estructuras definidas.`,
    Acuario: (n, h) => `Con Mercurio en Acuario en la casa ${h}, ${n} tiene una mente visionaria que piensa de manera no convencional y adelantada a su tiempo. Sus ideas son originales, a veces sorprendentes, y siempre apuntan hacia el futuro. La casa ${h} indica el área donde este pensamiento innovador es más activo. ${n} aprende mejor cuando puede explorar ideas nuevas sin restricciones.`,
    Piscis: (n, h) => `Con Mercurio en Piscis en la casa ${h}, ${n} tiene una mente intuitiva, imaginativa y profundamente conectada con el mundo de las emociones y los símbolos. Piensa a través de imágenes y metáforas más que de lógica lineal. La casa ${h} señala el área donde esta mente soñadora se expresa con más fluidez. ${n} aprende mejor a través del arte, la música y las historias.`,
  },
  Venus: {
    Aries: (n, h) => `Con Venus en Aries en la casa ${h}, ${n} expresa el afecto de manera directa, apasionada y sin rodeos. Sus demostraciones de amor son impulsivas y sinceras. La casa ${h} señala el área donde esta Venus ardiente busca conexión. ${n} necesita que sus afectos sean correspondidos con igual entusiasmo.`,
    Tauro: (n, h) => `Con Venus en Tauro en la casa ${h}, ${n} valora profundamente la estabilidad, el contacto físico y la belleza sensorial. Sus afectos son lentos en desarrollarse pero profundos y leales una vez establecidos. La casa ${h} indica el área donde esta Venus sensual busca placer y conexión. ${n} se siente amado a través del contacto físico y los rituales compartidos.`,
    Géminis: (n, h) => `Con Venus en Géminis en la casa ${h}, ${n} expresa el amor a través de las palabras, el juego intelectual y la variedad de experiencias compartidas. La casa ${h} señala el área donde esta Venus comunicativa busca conexión. ${n} necesita que quienes le rodean sean también sus amigos y compañeros de juego.`,
    Cáncer: (n, h) => `Con Venus en Cáncer en la casa ${h}, ${n} ama con una profundidad emocional que puede ser abrumadora para muchos. Cuida a quienes ama con devoción instintiva. La casa ${h} indica el área donde esta Venus maternal busca crear vínculos. ${n} necesita sentir que el hogar y la familia son sagrados.`,
    Leo: (n, h) => `Con Venus en Leo en la casa ${h}, ${n} ama de manera generosa, dramática y con un corazón completamente abierto. Sus expresiones de afecto son grandes, visibles y llenas de calor. La casa ${h} señala el área donde esta Venus radiante busca ser vista y amada. ${n} necesita que su amor sea celebrado.`,
    Virgo: (n, h) => `Con Venus en Virgo en la casa ${h}, ${n} expresa el amor a través del servicio y la atención al detalle. Para este niño, hacer algo concreto por quien ama es la mayor demostración de afecto. La casa ${h} indica el área donde esta Venus servicial busca conectar. ${n} se siente amado cuando sus necesidades son atendidas con dedicación.`,
    Libra: (n, h) => `Con Venus en Libra en la casa ${h}, ${n} valora la armonía, la justicia y la belleza en sus relaciones sobre todas las cosas. La casa ${h} señala el área donde esta Venus armoniosa busca conexión. ${n} necesita relaciones justas y que se le trate con elegancia y consideración.`,
    Escorpio: (n, h) => `Con Venus en Escorpio en la casa ${h}, ${n} ama con una intensidad y una lealtad que no admiten medias tintas. Sus afectos son totales, profundos y transformadores. La casa ${h} indica el área donde esta Venus intensa busca fusionarse. ${n} necesita vínculos auténticos donde pueda ser completamente honesto.`,
    Sagitario: (n, h) => `Con Venus en Sagitario en la casa ${h}, ${n} ama la libertad tanto como ama a las personas. Sus afectos son alegres, expansivos y conectados con la aventura compartida. La casa ${h} señala el área donde esta Venus aventurera busca conexión. ${n} necesita relaciones que respeten su independencia.`,
    Capricornio: (n, h) => `Con Venus en Capricornio en la casa ${h}, ${n} expresa el amor de manera reservada pero profundamente leal. Sus afectos se demuestran más con acciones consistentes que con palabras. La casa ${h} indica el área donde esta Venus práctica busca construir vínculos duraderos. ${n} necesita que quienes le rodean sean confiables y estables.`,
    Acuario: (n, h) => `Con Venus en Acuario en la casa ${h}, ${n} ama de manera original, independiente y profundamente igualitaria. Valora la amistad tanto como el amor, y la libertad como parte esencial de cualquier vínculo. La casa ${h} señala el área donde esta Venus libre busca conexión. ${n} necesita relaciones que respeten su singularidad.`,
    Piscis: (n, h) => `Con Venus en Piscis en la casa ${h}, ${n} ama con una dulzura y una compasión que trascienden lo ordinario. Sus afectos son idealizados, espirituales y llenos de una belleza casi mística. La casa ${h} indica el área donde esta Venus soñadora busca fusión amorosa. ${n} necesita amor incondicional y entornos hermosos.`,
  },
  Marte: {
    Aries: (n, h) => `Con Marte en Aries en la casa ${h}, ${n} tiene una energía vital que es pura y directa como una flecha. Actúa con decisión instintiva y su fuerza de voluntad es impresionante. La casa ${h} señala el área donde esta energía marciana se expresa con máxima intensidad. ${n} necesita salidas físicas regulares y actividades que le den la sensación de conquista inmediata.`,
    Tauro: (n, h) => `Con Marte en Tauro en la casa ${h}, ${n} tiene una energía que parece lenta al principio pero que, una vez activada, es prácticamente imparable. La casa ${h} indica el área donde esta perseverancia marciana construye más. ${n} actúa mejor cuando tiene tiempo suficiente para prepararse y metas que ofrezcan recompensa tangible.`,
    Géminis: (n, h) => `Con Marte en Géminis en la casa ${h}, ${n} canaliza su energía a través de las palabras, las ideas y la curiosidad constante. Su mente es el motor que impulsa sus acciones. La casa ${h} señala el área donde esta energía mental se despliega con más agilidad. ${n} necesita variedad y estimulación mental constante.`,
    Cáncer: (n, h) => `Con Marte en Cáncer en la casa ${h}, ${n} actúa desde las emociones: sus motivaciones más profundas están siempre ligadas a proteger lo que ama. La casa ${h} indica el área donde esta energía protectora es más intensa. ${n} necesita causas que le importen emocionalmente para dar lo mejor de sí mismo.`,
    Leo: (n, h) => `Con Marte en Leo en la casa ${h}, ${n} actúa con confianza, creatividad y un deseo de brillar que impulsa cada uno de sus esfuerzos. Su energía es dramática, generosa y necesita un escenario donde expresarse. La casa ${h} señala el área donde esta energía se despliega con más poder. ${n} necesita ser protagonista de sus propias aventuras.`,
    Virgo: (n, h) => `Con Marte en Virgo en la casa ${h}, ${n} dirige su energía hacia la perfección, el servicio y la mejora constante de todo lo que hace. La casa ${h} indica el área donde esta energía perfeccionista trabaja con más dedicación. ${n} necesita tareas concretas y la satisfacción de ver su trabajo bien hecho.`,
    Libra: (n, h) => `Con Marte en Libra en la casa ${h}, ${n} actúa de manera diplomática, considerada y siempre con el equilibrio en mente. No le gustan los conflictos directos y prefiere la negociación. La casa ${h} señala el área donde esta energía equilibrada busca acción. ${n} funciona mejor en trabajo colaborativo.`,
    Escorpio: (n, h) => `Con Marte en Escorpio en la casa ${h}, ${n} tiene una energía estratégica, intensa y extraordinariamente enfocada. Cuando se propone algo, no hay obstáculo que le detenga. La casa ${h} indica el área donde esta voluntad de acero actúa con más poder. ${n} necesita proyectos que le exijan profundizar y transformar.`,
    Sagitario: (n, h) => `Con Marte en Sagitario en la casa ${h}, ${n} actúa con entusiasmo, optimismo y un sentido de aventura que inspira a quienes le rodean. Su energía se renueva constantemente cuando hay exploración y libertad por delante. La casa ${h} señala el área donde esta energía aventurera es más viva. ${n} necesita espacio para moverse y explorar.`,
    Capricornio: (n, h) => `Con Marte en Capricornio en la casa ${h}, ${n} dirige su energía con una disciplina y una paciencia estratégica que resultan en logros notables. La casa ${h} indica el área donde esta energía ambiciosa construye con más solidez. ${n} necesita metas claras a largo plazo y la satisfacción de saber que sus esfuerzos tienen un propósito mayor.`,
    Acuario: (n, h) => `Con Marte en Acuario en la casa ${h}, ${n} actúa de manera original, independiente y orientada al bien colectivo. Su energía se activa cuando hay una causa justa o una idea innovadora que defender. La casa ${h} señala el área donde esta energía reformadora es más activa. ${n} necesita proyectos que desafíen el status quo.`,
    Piscis: (n, h) => `Con Marte en Piscis en la casa ${h}, ${n} actúa desde la intuición, la compasión y una conexión espiritual con sus motivaciones más profundas. Su energía es sutil pero persistente, como el agua que todo lo penetra. La casa ${h} indica el área donde esta energía fluida se expresa con más gracia. ${n} necesita que sus acciones estén conectadas con valores que siente en el alma.`,
  },
  Júpiter: {
    Aries: (n, h) => `Con Júpiter en Aries en la casa ${h}, ${n} encontrará su mayor crecimiento cuando se atreve a liderar e iniciar sin miedo. La suerte sonríe cuando actúa con valentía y sigue su primer impulso. La casa ${h} señala el área donde este crecimiento es más evidente y generoso. ${n} expande su potencial al emprender con confianza y celebrar cada nuevo comienzo.`,
    Tauro: (n, h) => `Con Júpiter en Tauro en la casa ${h}, ${n} atraerá abundancia a través de la perseverancia y el desarrollo de sus talentos naturales. La casa ${h} indica el área donde este flujo jupiteriano es más fértil. ${n} prospera cuando cultiva paciencia y confía en que la semilla que planta hoy florecerá en el tiempo justo.`,
    Géminis: (n, h) => `Con Júpiter en Géminis en la casa ${h}, ${n} encontrará su mayor crecimiento a través del conocimiento, la comunicación y las conexiones que establece. La casa ${h} señala el área donde esta sed de saber es más activa. ${n} prospera en entornos ricos en información y diversidad de estímulos.`,
    Cáncer: (n, h) => `Con Júpiter en Cáncer en la casa ${h}, ${n} encontrará su mayor crecimiento a través de los vínculos familiares y el cultivo de la intuición emocional. La abundancia llega cuando actúa desde el amor y la compasión. La casa ${h} indica el área donde este crecimiento es más nutritivo.`,
    Leo: (n, h) => `Con Júpiter en Leo en la casa ${h}, ${n} expandirá su potencial a través de la creatividad y la autoexpresión auténtica. La suerte acompaña cuando brilla sin pedir permiso. La casa ${h} señala el área donde este crecimiento generoso es más visible. ${n} prospera en entornos que celebran su singularidad.`,
    Virgo: (n, h) => `Con Júpiter en Virgo en la casa ${h}, ${n} encontrará su mayor crecimiento a través del servicio y el perfeccionamiento de habilidades. La abundancia llega cuando aplica su talento analítico con dedicación. La casa ${h} indica el área donde este crecimiento se manifiesta con más utilidad.`,
    Libra: (n, h) => `Con Júpiter en Libra en la casa ${h}, ${n} encontrará su mayor crecimiento a través de las relaciones y la búsqueda de justicia y armonía. La casa ${h} señala el área donde este crecimiento florece en las conexiones. ${n} prospera en entornos cooperativos y justos.`,
    Escorpio: (n, h) => `Con Júpiter en Escorpio en la casa ${h}, ${n} encontrará su mayor crecimiento a través de las transformaciones profundas y la investigación. La abundancia llega cuando no le teme a la profundidad. La casa ${h} indica el área donde este crecimiento actúa con más intensidad transformadora.`,
    Sagitario: (n, h) => `Con Júpiter en Sagitario en la casa ${h}, ${n} tiene uno de los mejores regalos jupiterianos posibles: la expansión natural a través de la aventura, el conocimiento y la fe en la vida. La casa ${h} señala el área donde este crecimiento abundante es más generoso.`,
    Capricornio: (n, h) => `Con Júpiter en Capricornio en la casa ${h}, ${n} encontrará su mayor crecimiento a través de la disciplina y el trabajo constante hacia metas elevadas. La abundancia llega con paciencia y esfuerzo sostenido. La casa ${h} indica el área donde este crecimiento construye con más solidez.`,
    Acuario: (n, h) => `Con Júpiter en Acuario en la casa ${h}, ${n} encontrará su mayor crecimiento a través de la innovación y la colaboración comunitaria. La abundancia llega cuando actúa para el bien colectivo. La casa ${h} señala el área donde este crecimiento es más visionario.`,
    Piscis: (n, h) => `Con Júpiter en Piscis en la casa ${h}, ${n} encontrará su mayor crecimiento a través de la espiritualidad, la creatividad artística y la compasión sin límites. La abundancia llega cuando confía en su intuición. La casa ${h} indica el área donde este crecimiento es más místico y generoso.`,
  },
  Saturno: {
    Aries: (n, h) => `Con Saturno en Aries en la casa ${h}, ${n} aprenderá sus lecciones más profundas en el área de la autoafirmación y el liderazgo. Al principio puede dudar de sí mismo, pero con el tiempo desarrollará una valentía templada por la experiencia. La casa ${h} señala el área donde este aprendizaje es más exigente. Este emplazamiento construye con el tiempo una fortaleza personal extraordinaria.`,
    Tauro: (n, h) => `Con Saturno en Tauro en la casa ${h}, ${n} encontrará sus mayores lecciones en el ámbito de los recursos, la seguridad material y la paciencia. La casa ${h} indica el área donde estas lecciones son más concretas. Este emplazamiento construye con el tiempo una base material y emocional verdaderamente sólida.`,
    Géminis: (n, h) => `Con Saturno en Géminis en la casa ${h}, ${n} aprenderá sus lecciones más importantes en el área del aprendizaje y la comunicación. Puede que al principio sienta inseguridad al expresarse, pero desarrollará una mente disciplinada y profundamente capaz. La casa ${h} señala el área donde este rigor mental es más necesario.`,
    Cáncer: (n, h) => `Con Saturno en Cáncer en la casa ${h}, ${n} aprenderá sus lecciones más profundas en el ámbito emocional y familiar. Con el tiempo construirá una fortaleza emocional y un sentido de hogar que vendrán de adentro hacia afuera. La casa ${h} indica el área donde estas lecciones emotivas son más activas.`,
    Leo: (n, h) => `Con Saturno en Leo en la casa ${h}, ${n} aprenderá sus lecciones más importantes en el área de la autoexpresión y la confianza en sí mismo. Puede dudar de su brillo en la infancia, pero con el tiempo desarrollará una autoconfianza genuina y duradera. La casa ${h} señala el área donde estas lecciones de autenticidad son más intensas.`,
    Virgo: (n, h) => `Con Saturno en Virgo en la casa ${h}, ${n} aprenderá sus lecciones más profundas en el área del servicio, la salud y el orden. El perfeccionismo puede ser su mayor desafío y su mayor fortaleza al mismo tiempo. La casa ${h} indica el área donde este rigor saturnino es más presente.`,
    Libra: (n, h) => `Con Saturno en Libra en la casa ${h}, ${n} aprenderá sus lecciones más importantes en el área de las relaciones y la justicia. Puede que los vínculos le exijan mayor esfuerzo que a otros, pero con el tiempo construirá relaciones profundamente maduras. La casa ${h} señala el área donde estas lecciones relacionales son más activas.`,
    Escorpio: (n, h) => `Con Saturno en Escorpio en la casa ${h}, ${n} aprenderá sus lecciones más profundas en el área de la transformación y el poder personal. Enfrentar lo que asusta puede ser su camino de mayor crecimiento. La casa ${h} indica el área donde estas lecciones de transformación son más intensas.`,
    Sagitario: (n, h) => `Con Saturno en Sagitario en la casa ${h}, ${n} aprenderá sus lecciones más importantes en el área de las creencias y la filosofía. La fe le exigirá un recorrido más largo antes de encontrar su propia verdad. La casa ${h} señala el área donde estas lecciones filosóficas son más presentes.`,
    Capricornio: (n, h) => `Con Saturno en Capricornio en la casa ${h}, ${n} tiene a Saturno en su domicilio, lo que significa que las lecciones de disciplina y responsabilidad serán intensas pero profundamente formativas. La casa ${h} indica el área donde esta madurez temprana se expresa con más fuerza.`,
    Acuario: (n, h) => `Con Saturno en Acuario en la casa ${h}, ${n} aprenderá sus lecciones más importantes en el área de la comunidad y la responsabilidad social. Puede que encontrar su lugar en el grupo sea un desafío al principio. La casa ${h} señala el área donde estas lecciones comunitarias son más activas.`,
    Piscis: (n, h) => `Con Saturno en Piscis en la casa ${h}, ${n} aprenderá sus lecciones más profundas en el área de los límites y la espiritualidad. Poner límites sin perder compasión será uno de sus aprendizajes más importantes. La casa ${h} indica el área donde estas lecciones espirituales son más presentes.`,
  },
  Urano: {
    Aries: (n, h) => `Con Urano en Aries en la casa ${h}, ${n} porta la energía de una generación que llegó a redefinir el concepto de identidad individual. En la casa ${h} esta originalidad se expresa en el área de vida más visible para ${n}. Desde pequeño puede demostrar una independencia y originalidad que sorprenden a quienes le rodean.`,
    Tauro: (n, h) => `Con Urano en Tauro en la casa ${h}, ${n} porta la energía de una generación que llegó a transformar los sistemas económicos. En la casa ${h} este impulso renovador se expresa en áreas concretas de la vida de ${n}. Puede tener ideas muy originales sobre los recursos y cómo construir seguridad de maneras nuevas.`,
    Géminis: (n, h) => `Con Urano en Géminis en la casa ${h}, ${n} tiene una mente que puede hacer conexiones sorprendentes entre ideas que nadie más relacionaría. La casa ${h} señala el área donde esta originalidad mental se expresa con más libertad. Su forma de pensar y comunicar es genuinamente original.`,
    Cáncer: (n, h) => `Con Urano en Cáncer en la casa ${h}, ${n} porta la energía de una generación que llegó a redefinir el concepto de hogar y familia. En la casa ${h} esta renovación se expresa en cómo ${n} construye sus vínculos más íntimos.`,
    Leo: (n, h) => `Con Urano en Leo en la casa ${h}, ${n} tiene una creatividad genuinamente revolucionaria y una forma de expresarse que no sigue ningún molde conocido. La casa ${h} señala el área donde esta originalidad creativa es más activa.`,
    Virgo: (n, h) => `Con Urano en Virgo en la casa ${h}, ${n} porta ideas innovadoras sobre la salud, el servicio y el trabajo. La casa ${h} indica el área donde esta innovación práctica es más visible en la vida de ${n}.`,
    Libra: (n, h) => `Con Urano en Libra en la casa ${h}, ${n} porta la energía de una generación que llegó a redefinir las relaciones y la justicia. En la casa ${h} esta renovación relacional se expresa con más intensidad. ${n} puede tener ideas muy progresistas sobre cómo deberían funcionar los vínculos.`,
    Escorpio: (n, h) => `Con Urano en Escorpio en la casa ${h}, ${n} porta una energía generacional profundamente transformadora en el ámbito del poder y los recursos compartidos. La casa ${h} señala el área donde esta transformación radical es más activa en la vida de ${n}.`,
    Sagitario: (n, h) => `Con Urano en Sagitario en la casa ${h}, ${n} porta la energía de una generación que llegó a expandir los horizontes de la filosofía y la espiritualidad. En la casa ${h} este impulso expansivo se expresa con originalidad.`,
    Capricornio: (n, h) => `Con Urano en Capricornio en la casa ${h}, ${n} porta la energía de una generación que llegó a transformar las estructuras de poder. La casa ${h} indica el área donde esta renovación estructural es más activa en la vida de ${n}.`,
    Acuario: (n, h) => `Con Urano en Acuario en la casa ${h}, ${n} tiene a Urano en su domicilio, lo que amplifica enormemente su originalidad y su visión futurista. La casa ${h} señala el área donde esta energía innovadora es más intensa. ${n} porta una visión vanguardista que puede transformar su entorno.`,
    Piscis: (n, h) => `Con Urano en Piscis en la casa ${h}, ${n} porta la energía de una generación que llegó a transformar la espiritualidad. En la casa ${h} esta renovación espiritual se expresa en la vida de ${n}. Puede tener una espiritualidad genuinamente original y liberada de dogmas.`,
  },
  Neptuno: {
    Aries: (n, h) => `Con Neptuno en Aries en la casa ${h}, ${n} lleva en su alma la búsqueda de un ideal de valentía que trasciende el ego individual. En la casa ${h} esta energía se expresa a través de una visión inspirada del liderazgo. ${n} puede tener una conexión intuitiva especial con las causas que requieren coraje.`,
    Tauro: (n, h) => `Con Neptuno en Tauro en la casa ${h}, ${n} lleva una sensibilidad artística especial hacia la belleza de lo tangible: la naturaleza, la música, las artes plásticas. La casa ${h} indica el área donde esta receptividad creativa es más intensa.`,
    Géminis: (n, h) => `Con Neptuno en Géminis en la casa ${h}, ${n} tiene una mente que se mueve entre la lógica y la intuición con fluidez poética. En la casa ${h} esta dualidad se expresa con más claridad. ${n} puede tener un don especial para la escritura creativa o la comunicación que mezcla lo racional con lo místico.`,
    Cáncer: (n, h) => `Con Neptuno en Cáncer en la casa ${h}, ${n} tiene una sensibilidad espiritual especialmente ligada al amor familiar y al hogar sagrado. La casa ${h} señala el área donde esta receptividad emocional-espiritual es más activa. ${n} puede percibir los estados emocionales ajenos con una precisión casi sobrenatural.`,
    Leo: (n, h) => `Con Neptuno en Leo en la casa ${h}, ${n} lleva una visión inspirada de la creatividad como acto sagrado. La casa ${h} indica el área donde esta inspiración es más activa. ${n} puede tener dones artísticos con una dimensión espiritual que va más allá del simple talento.`,
    Virgo: (n, h) => `Con Neptuno en Virgo en la casa ${h}, ${n} lleva una sensibilidad especial hacia el servicio como acto espiritual y hacia la salud holística. La casa ${h} señala el área donde esta devoción es más activa. ${n} puede ser especialmente receptivo a las necesidades de otros.`,
    Libra: (n, h) => `Con Neptuno en Libra en la casa ${h}, ${n} lleva una visión idealizada de lo que pueden ser las relaciones y la justicia en el mundo. La casa ${h} indica el área donde esta idealización es más activa. ${n} puede tener un don especial para crear armonía en sus vínculos.`,
    Escorpio: (n, h) => `Con Neptuno en Escorpio en la casa ${h}, ${n} lleva una profundidad espiritual y una conexión con los misterios de la existencia poco común. La casa ${h} señala el área donde esta profundidad es más intensa. ${n} puede tener dones para la percepción de lo oculto.`,
    Sagitario: (n, h) => `Con Neptuno en Sagitario en la casa ${h}, ${n} lleva la energía de una generación que soñó con expandir los horizontes espirituales de la humanidad. La casa ${h} indica el área donde esta visión espiritual expansiva es más activa. ${n} puede tener una espiritualidad naturalmente universal y sin fronteras dogmáticas.`,
    Capricornio: (n, h) => `Con Neptuno en Capricornio en la casa ${h}, ${n} lleva la energía de una generación que buscó espiritualizar las estructuras de poder. La casa ${h} señala el área donde esta tensión entre lo práctico y lo espiritual es más activa. ${n} puede tener una visión profunda sobre cómo construir con propósito y sentido.`,
    Acuario: (n, h) => `Con Neptuno en Acuario en la casa ${h}, ${n} porta la visión de una humanidad conectada espiritualmente a través de la innovación. La casa ${h} indica el área donde esta visión colectiva es más activa. ${n} puede tener ideales profundos sobre un mundo más justo.`,
    Piscis: (n, h) => `Con Neptuno en Piscis en la casa ${h}, ${n} tiene a Neptuno en su domicilio, lo que potencia enormemente su sensibilidad espiritual, artística e intuitiva. La casa ${h} señala el área donde esta profundidad es más intensa. ${n} puede tener dones excepcionales en el arte, la música o cualquier campo que requiera conexión con lo invisible.`,
  },
  Plutón: {
    Aries: (n, h) => `Con Plutón en Aries en la casa ${h}, la generación de ${n} lleva la misión de transformar radicalmente los conceptos de identidad y poder individual. En la casa ${h} esta energía plutoniana se expresa en el área más profunda de transformación personal de ${n}. Este emplazamiento habla de una capacidad de renovación total en el área señalada.`,
    Tauro: (n, h) => `Con Plutón en Tauro en la casa ${h}, la generación de ${n} lleva la misión de transformar profundamente los sistemas económicos y la relación con la tierra. En la casa ${h} esta energía encuentra su campo de transformación más intenso.`,
    Géminis: (n, h) => `Con Plutón en Géminis en la casa ${h}, la generación de ${n} lleva la misión de transformar los sistemas de comunicación y conocimiento. La casa ${h} señala el área donde esta transformación mental es más activa en ${n}.`,
    Cáncer: (n, h) => `Con Plutón en Cáncer en la casa ${h}, la generación de ${n} lleva la misión de transformar los conceptos de familia y nutrición emocional. La casa ${h} indica el área donde esta transformación íntima es más activa. ${n} puede tener una capacidad especial para sanar heridas familiares.`,
    Leo: (n, h) => `Con Plutón en Leo en la casa ${h}, la generación de ${n} lleva la misión de transformar la expresión del poder personal y la creatividad. La casa ${h} señala el área donde esta transformación del yo es más activa. ${n} puede tener un carisma que transforma a quienes le rodean.`,
    Virgo: (n, h) => `Con Plutón en Virgo en la casa ${h}, la generación de ${n} lleva la misión de transformar los sistemas de salud y trabajo. La casa ${h} indica el área donde esta transformación práctica es más activa. ${n} puede tener una capacidad de análisis que va a la raíz de los problemas.`,
    Libra: (n, h) => `Con Plutón en Libra en la casa ${h}, la generación de ${n} lleva la misión de transformar profundamente los conceptos de justicia y relación. La casa ${h} señala el área donde esta transformación relacional es más activa.`,
    Escorpio: (n, h) => `Con Plutón en Escorpio en la casa ${h}, ${n} tiene a Plutón en su domicilio, lo que intensifica enormemente su capacidad de transformación y su conexión con los misterios de la existencia. La casa ${h} señala el área donde esta energía es más poderosa. Este emplazamiento habla de una capacidad de muerte y renacimiento que pocas personas poseen.`,
    Sagitario: (n, h) => `Con Plutón en Sagitario en la casa ${h}, la generación de ${n} lleva la misión de transformar profundamente los sistemas de creencias y educación. La casa ${h} indica el área donde esta transformación filosófica es más activa en ${n}.`,
    Capricornio: (n, h) => `Con Plutón en Capricornio en la casa ${h}, la generación de ${n} lleva la misión de transformar radicalmente las estructuras de poder y las instituciones. La casa ${h} señala el área donde esta transformación estructural es más activa. ${n} puede tener una capacidad innata para entender y transformar el poder.`,
    Acuario: (n, h) => `Con Plutón en Acuario en la casa ${h}, la generación de ${n} lleva la misión de transformar radicalmente la tecnología y los sistemas sociales para el bien colectivo. La casa ${h} indica el área donde esta transformación visionaria es más activa. ${n} porta una energía que puede catalizar cambios profundos en los sistemas que rodean a las personas.`,
    Piscis: (n, h) => `Con Plutón en Piscis en la casa ${h}, la generación de ${n} lleva la misión de transformar profundamente la espiritualidad y la conexión con lo invisible. La casa ${h} señala el área donde esta transformación espiritual es más activa en ${n}.`,
  },
};

export function getPlanetText(planet: string, sign: string, house: number, childName: string, adjSuffix: string): string {
  const fn = PLANET_INTERPRETATIONS[planet]?.[sign];
  if (fn) return fn(childName, house, adjSuffix);
  return `Con ${planet} en ${sign} en la casa ${house}, ${childName} tiene una energía única que combina la esencia de ${planet} con las cualidades de ${sign} en el área de vida señalada por la casa ${house}.`;
}

type ParentingFn = (childName: string, adjSuffix: string) => string[];

export const PARENTING_GUIDE: Record<string, ParentingFn> = {
  Aries: (n) => [
    `Ofrece a ${n} actividades físicas y deportes donde pueda liberar su energía de manera positiva. Un cuerpo activo es su camino hacia la paz interior.`,
    `Dale responsabilidades reales desde pequeño/a. Los niños Aries necesitan sentir que sus acciones importan y que pueden liderar algo.`,
    `Evita decirle "no" sin explicación. ${n} necesita entender el por qué de los límites para aceptarlos genuinamente.`,
    `Celebra su iniciativa aunque no llegue a buen puerto. El intento valiente merece reconocimiento tanto como el resultado.`,
    `Enseña a ${n} a completar lo que empieza antes de iniciar algo nuevo. Esta es su lección de vida más importante en la infancia.`,
    `Nunca le humilles delante de otros. Su orgullo es profundo y una vergüenza pública puede dejar heridas que tardan en sanar.`,
    `Dale elecciones dentro de límites seguros: "¿Quieres hacer la tarea ahora o en 20 minutos?" El control sobre pequeñas decisiones le da la autonomía que necesita.`,
    `Muéstrale con el ejemplo que la valentía no es ausencia de miedo, sino actuar a pesar de él.`,
  ],
  Tauro: (n) => [
    `Mantén rutinas estables y predecibles. Para ${n}, la seguridad se construye con horarios, ritmos y espacios conocidos.`,
    `No le apresures. Un niño Tauro necesita su propio tiempo para procesar, decidir y actuar. Presionarle genera resistencia y terquedad.`,
    `Conecta el aprendizaje con los sentidos: texturas, sabores, música, naturaleza. ${n} aprende y recuerda mejor a través de experiencias sensoriales.`,
    `Enséñale el valor del dinero desde pequeño/a con una alcancía y pequeñas responsabilidades. Tiene talento natural para los recursos.`,
    `Respeta sus posesiones. ${n} tiene un sentido muy desarrollado de "lo mío" y necesita que se valore lo que le pertenece.`,
    `Usa la naturaleza como espacio de regulación emocional: caminar descalzo en el pasto, tocar tierra, estar cerca de plantas y animales.`,
    `Sé consistente en tu palabra. ${n} necesita poder contar contigo de manera absoluta para sentirse seguro/a.`,
    `Celebra sus logros con experiencias placenteras: una comida especial, un paseo a su lugar favorito. El placer sensorial es su lenguaje de celebración.`,
  ],
  Géminis: (n) => [
    `Alimenta la curiosidad de ${n} sin límites: libros, documentales, museos, conversaciones con personas de distintos campos. Su mente es su mayor regalo.`,
    `Hazte preguntas junto a él/ella. Los niños Géminis aprenden más con quien explora con ellos que con quien solo da respuestas.`,
    `Permite que cambie de actividades con más frecuencia que otros niños. Su mente necesita variedad para mantenerse comprometida y feliz.`,
    `Enseña la diferencia entre la información y la sabiduría. ${n} acumula datos con facilidad; ayúdale a profundizar y conectar los puntos.`,
    `Dale tiempo para hablar. Los niños Géminis procesan el mundo a través de las palabras. Escuchar sus monólogos es una forma de amor.`,
    `Introduce el aprendizaje de idiomas desde temprano. Tiene una capacidad especial para los lenguajes y la comunicación.`,
    `Ayúdale a terminar lo que empieza. Su tendencia es saltar a lo próximo; completar proyectos es parte de su aprendizaje clave.`,
    `Nunca desestimes sus ideas por "disparatadas". La mente de ${n} conecta lo que otros no ven, y ese es precisamente su don.`,
  ],
  Cáncer: (n) => [
    `El hogar es el corazón de todo para ${n}. Crea rituales familiares: la cena juntos, el cuento antes de dormir, las tradiciones que repiten año tras año.`,
    `Valida sus emociones antes de buscar soluciones. ${n} necesita sentirse comprendido/a emocionalmente antes de poder escuchar razones.`,
    `Nunca lo/la hagas sentir avergonzado/a por llorar o por necesitar consuelo. Su sensibilidad es una fortaleza, no una debilidad.`,
    `Incluye a ${n} en los rituales de cuidado del hogar: cocinar, ordenar, decorar. La participación en el nido familiar le hace sentir seguro/a.`,
    `Sé consciente de tu propio estado emocional. ${n} absorbe el ambiente familiar y tu paz interior es directamente su paz interior.`,
    `Enséñale a poner límites desde el amor, no desde el miedo. Proteger su espacio emocional es uno de sus grandes aprendizajes.`,
    `Comparte recuerdos familiares y fotos del pasado. Los niños Cáncer se nutren de la historia familiar y el sentido de continuidad.`,
    `Dale tiempo para retirarse y recargar. Después de mucha estimulación social, ${n} necesita su espacio seguro para volver a sí mismo/a.`,
  ],
  Leo: (n) => [
    `Celebra sus logros con genuino entusiasmo, incluso los pequeños. El reconocimiento auténtico es el alimento esencial de ${n}.`,
    `Dale espacios para brillar: que actúe, cante, baile, cuente historias. ${n} necesita un escenario donde su luz sea bienvenida.`,
    `Nunca lo/la humilles en público ni compares su brillo con el de otros. Una herida al orgullo de ${n} puede tardar años en sanar.`,
    `Ayúdale a distinguir entre actuar para recibir atención y expresarse desde la autenticidad. Esta distinción cambia toda su trayectoria de vida.`,
    `Enséñale generosidad desde pequeño/a. Los niños Leo que aprenden a dar su luz sin necesidad de reciprocidad inmediata son los más felices.`,
    `Trátale como el/la líder que es, dándole responsabilidades acordes a su edad. Ser responsable de algo le hace sentir importante.`,
    `Comparte tu propio tiempo de calidad con ${n} de manera regular. Saber que eres su audiencia más importante le da una seguridad profunda.`,
    `Enseña con el ejemplo que la verdadera grandeza viene de dentro, no de los aplausos. Este es el camino hacia su madurez.`,
  ],
  Virgo: (n) => [
    `Establece rutinas claras y organizadas. Para ${n}, saber qué viene después reduce la ansiedad y le permite dar lo mejor de sí mismo/a.`,
    `Nunca ridiculices su perfeccionismo. Lo que para otros es "exagerado", para ${n} es integridad. Ayúdale a ser perfeccionista con compasión.`,
    `Enseña la diferencia entre intentarlo bien y hacerlo perfectamente. El miedo a equivocarse puede bloquearle; el permiso para aprender lo libera.`,
    `Involúcrale en tareas concretas y útiles del hogar. Los niños Virgo encuentran satisfacción profunda en ser genuinamente útiles.`,
    `Cuida su salud digestiva: este signo tiende a somatizar el estrés. Las rutinas de comida y ejercicio son especialmente importantes.`,
    `Dale proyectos con pasos claros y metas medibles. ${n} trabaja con más confianza cuando sabe exactamente qué se espera de él/ella.`,
    `Celebra el proceso, no solo el resultado. Reconocer el esfuerzo y la dedicación es más valioso para ${n} que el resultado final.`,
    `Ayúdale a expresar sus preocupaciones con palabras. Los niños Virgo pueden preocuparse en silencio; crear espacios de conversación regular previene la ansiedad acumulada.`,
  ],
  Libra: (n) => [
    `Crea un hogar donde reine la armonía. Las discusiones frecuentes o la tensión constante afectan profundamente a ${n} en su sentido de bienestar.`,
    `Enseña a tomar decisiones. Los niños Libra pueden paralizarse ante las opciones; práctica de decisiones pequeñas diarias les da confianza.`,
    `Modela la resolución de conflictos de manera justa y respetuosa. ${n} aprenderá a manejar sus propias diferencias observando cómo los adultos lo hacen.`,
    `Dale acceso al arte, la música y la belleza desde pequeño/a. Su sentido estético es un lenguaje que necesita ser cultivado.`,
    `Ayúdale a encontrar su propia opinión antes de preguntar la de otros. La tendencia de Libra es adaptar su punto de vista al de quien más respeta.`,
    `Enséñale que decir "no" no rompe la armonía; a veces la crea. Poner límites es también una forma de cuidar el equilibrio.`,
    `Involúcrale en actividades sociales y grupales donde pueda desarrollar sus habilidades diplomáticas naturales.`,
    `Honra su necesidad de equidad. Si siente que algo es injusto, escúchale con atención. Su sentido de la justicia es profundamente real para él/ella.`,
  ],
  Escorpio: (n) => [
    `Sé absolutamente honesto/a con ${n}. Los niños Escorpio detectan la mentira con una precisión asombrosa, y la traición de la confianza les afecta de por vida.`,
    `Respeta su privacidad y su mundo interior. No todo en ${n} está disponible para ser visto; su vida interior necesita ser un espacio sagrado.`,
    `No le presiones a expresar lo que siente. La profundidad emocional de Escorpio necesita tiempo para salir. Presionar cierra la puerta.`,
    `Enséñale que la vulnerabilidad es poder, no debilidad. Este es uno de los aprendizajes más liberadores para un niño Escorpio.`,
    `Ayúdale a canalizar su intensidad en proyectos apasionantes: investigar, crear, transformar algo. La intensidad sin canal constructivo puede volverse destructiva.`,
    `Establece límites firmes y consistentes. Los niños Escorpio necesitan saber hasta dónde llegan los límites; los respetan cuando son genuinos y constantes.`,
    `Habla de los temas "difíciles" con naturalidad: la muerte, el cambio, los secretos. Escorpio necesita que la oscuridad pueda nombrarse.`,
    `Celebra su profundidad y su capacidad de ver más allá de lo superficial. Este es su mayor don y necesita ser reconocido como tal.`,
  ],
  Sagitario: (n) => [
    `Dale libertad para explorar, equivocarse y aprender de sus propias experiencias. Un Sagitario encajonado en demasiadas reglas se apaga.`,
    `Expande su mundo: viajes, culturas diferentes, idiomas, religiones, filosofías. ${n} necesita horizontes amplios para sentirse vivo/a.`,
    `Enseña con historias y aventuras, no con lecciones abstractas. Su mente aprende mejor cuando el conocimiento tiene sabor de aventura.`,
    `Honra sus preguntas existenciales, por más grandes que parezcan para su edad. "¿Por qué existimos?" es una pregunta genuina de ${n}.`,
    `Ayúdale a aprender el valor de los compromisos. La tendencia Sagitario es moverse hacia lo próximo; terminar lo que empieza es un aprendizaje clave.`,
    `Sé honesto/a en tus promesas. Un Sagitario que ve a sus adultos no cumplir sus palabras pierde la fe en los compromisos.`,
    `Involúcrale en actividades al aire libre y deportes que requieran movilidad. Su cuerpo necesita tanto espacio como su mente.`,
    `Comparte con ${n} tus propias búsquedas de sentido. Saber que sus preguntas son compartidas le da una profunda sensación de compañía en el camino.`,
  ],
  Capricornio: (n) => [
    `Ofrece a ${n} responsabilidades reales acordes a su edad. Los niños Capricornio florecen cuando se les confía algo importante.`,
    `Reconoce explícitamente su esfuerzo y dedicación. Más que el talento innato, lo que necesita que sea reconocida es su capacidad de trabajo.`,
    `Enseña que el descanso es parte del logro, no su contrario. Los Capricornios pueden ser duros consigo mismos; el permiso para descansar es un regalo.`,
    `Ayúdale a conectar sus metas con un "para qué" más profundo. La disciplina de Capricornio se sostiene mejor cuando tiene propósito claro.`,
    `Equilibra el enfoque en los logros con el juego puro y sin propósito. ${n} también necesita tiempo para ser niño/a sin que nada sea evaluado.`,
    `Sé paciente con su ritmo. Los Capricornios trabajan lento y bien; la prisa rompe su proceso natural de excelencia.`,
    `Modela una relación sana con el fracaso. Que ${n} vea que los adultos también se equivocan y siguen adelante es un regalo que transforma su vida.`,
    `Habla sobre el futuro con optimismo y planificación. Los niños Capricornio se sienten seguros cuando hay un plan y esperanza en el horizonte.`,
  ],
  Acuario: (n) => [
    `Respeta su necesidad de ser diferente. ${n} no encajará en todos los moldes, y eso no es un problema: es su mayor fortaleza.`,
    `Estimula su pensamiento crítico: cuestiona normas junto a él/ella, analiza situaciones desde múltiples perspectivas. Su mente es reformadora por naturaleza.`,
    `Dale espacio para sus amistades y actividades grupales. Los niños Acuario se nutren especialmente del sentido de pertenencia a comunidades que comparten sus valores.`,
    `Introduce la tecnología, la ciencia y las innovaciones desde temprano. Su mente está naturalmente conectada con el futuro.`,
    `Respeta su necesidad de soledad e independencia. Un Acuario que tiene su espacio propio es un Acuario que puede conectarse mejor con otros.`,
    `Evita las etiquetas rígidas. ${n} es fluido/a en su identidad y necesita libertad para explorar quién es sin definiciones permanentes.`,
    `Enseña que los sentimientos son tan válidos como los argumentos. La tendencia Acuario es intelectualizar las emociones; ayúdale a también sentirlas.`,
    `Involúcrale en causas sociales y humanitarias desde pequeño/a. Saber que puede contribuir al bien del mundo activa lo mejor de su naturaleza.`,
  ],
  Piscis: (n) => [
    `Protege el espacio emocional de ${n}. Es extremadamente sensible a los ambientes tensos, las discusiones y las energías negativas. Un hogar en paz es su mayor regalo.`,
    `Nutre su mundo artístico y creativo: música, pintura, danza, escritura. El arte es su idioma nativo y una forma de regulación emocional.`,
    `Enseña límites con amor. Los niños Piscis tienden a absorber el dolor ajeno; aprender a sentir sin perderse es uno de sus aprendizajes más importantes.`,
    `Honra su vida interior y su mundo imaginario. Lo que para otros puede parecer "distracción" es, para ${n}, una forma genuina de procesar la realidad.`,
    `Sé paciente con su timidez o su necesidad de tiempo para adaptarse a nuevas situaciones. No le empujes; acompáñale.`,
    `Introduce prácticas de conexión espiritual acordes a su edad: meditación simple, contacto con la naturaleza, rituales de gratitud.`,
    `Ayúdale a distinguir sus emociones de las de los demás. "¿Esto que sientes es tuyo o lo absorbiste del ambiente?" es una pregunta que le da herramientas para toda la vida.`,
    `Rodéale de personas y ambientes que le eleven. ${n} es como una esponja que absorbe el tono de lo que le rodea, para bien y para mal.`,
  ],
};

export const AFFIRMATIONS_BY_SUN: Record<string, string[]> = {
  Aries: [
    'Soy valiente. Mi coraje abre caminos que otros aún no pueden ver.',
    'Confío en mis impulsos. Mi primer instinto es una guía poderosa.',
    'Soy un líder natural. Mi energía inspira a quienes me rodean.',
    'Merezco comenzar de nuevo cuantas veces sea necesario.',
    'Mi energía es un regalo. La uso para crear, no para destruir.',
    'Aprendo de mis errores y sigo adelante con la cabeza en alto.',
    'Soy fuerte y gentil al mismo tiempo. Las dos cosas caben en mí.',
    'Mi entusiasmo es contagioso y hace que el mundo sea más emocionante.',
    'Tengo el poder de iniciar cosas grandes. Confío en mi capacidad.',
    'Soy exactamente quien necesita ser en este momento de mi vida.',
  ],
  Tauro: [
    'Soy un árbol de raíces profundas. Mi estabilidad es mi fortaleza.',
    'Merezco belleza, comodidad y amor en mi vida.',
    'Soy paciente. Las cosas buenas llegan cuando están listas.',
    'Mi cuerpo es sabio. Escucho lo que me pide con amor.',
    'Construyo cosas duraderas con mis manos y mi corazón.',
    'Soy confiable. Las personas a mi alrededor saben que pueden contar conmigo.',
    'Disfruto cada momento presente. La vida es este instante.',
    'Mi determinación es silenciosa pero imparable.',
    'Soy abundante. La generosidad de la vida fluye hacia mí.',
    'Merezco disfrutar de todo lo bueno que la vida tiene para darme.',
  ],
  Géminis: [
    'Mi mente brillante conecta ideas que otros no pueden ver.',
    'Las preguntas que hago son tan valiosas como las respuestas que encuentro.',
    'Soy curioso/a por naturaleza y eso me hace extraordinario/a.',
    'Tengo el don de comunicar con claridad y gracia.',
    'La variedad de mis intereses es una riqueza, no una debilidad.',
    'Aprendo con rapidez y comparto lo que sé con generosidad.',
    'Mi mente es ágil y adaptable ante cualquier situación.',
    'Soy un/a puente entre personas e ideas diferentes.',
    'Tengo palabras para todo lo que siento y todo lo que pienso.',
    'Soy un/a explorador/a de ideas y el mundo me abre sus puertas.',
  ],
  Cáncer: [
    'Mi corazón amoroso es mi mayor fortaleza.',
    'Mis emociones son información valiosa, no debilidades.',
    'Merezco sentirme seguro/a, amado/a y protegido/a siempre.',
    'Nutro a quienes amo y también me nutro a mí mismo/a.',
    'Mi intuición es un regalo. Confío en lo que siento.',
    'El hogar que llevo en mi corazón me acompaña a todas partes.',
    'Soy capaz de sanar lo que me duele con amor y paciencia.',
    'Mi sensibilidad me permite conectar con los demás de manera profunda.',
    'Soy amado/a incondicionalmente, tal como soy.',
    'Tengo raíces profundas que me sostienen en cualquier tormenta.',
  ],
  Leo: [
    'Soy luz. Tengo permiso para brillar sin pedir disculpas.',
    'Mi creatividad es única e irrepetible en el universo.',
    'Soy generoso/a con mi amor y mi alegría.',
    'Merezco ser visto/a, escuchado/a y celebrado/a.',
    'Mi corazón grande ilumina todo lo que toca.',
    'Lidero desde el amor, no desde el miedo.',
    'Soy orgulloso/a de quien soy y de lo que puedo llegar a ser.',
    'Inspiro a otros con mi autenticidad y mi valentía.',
    'Mi presencia hace que los espacios sean más cálidos y alegres.',
    'Tengo permiso de brillar. El mundo necesita mi luz.',
  ],
  Virgo: [
    'Mi capacidad de mejorar las cosas es un regalo para el mundo.',
    'Soy útil, confiable y dedicado/a.',
    'Me permito equivocarme. Los errores son parte del aprendizaje.',
    'Cuido mi cuerpo y mi mente porque me lo merezco.',
    'Mis logros son el resultado de mi esfuerzo y dedicación.',
    'Sirvo desde el amor, no desde la obligación.',
    'Soy suficientemente bueno/a. No necesito ser perfecto/a para ser valioso/a.',
    'Mi atención al detalle crea obras que duran.',
    'Tengo el don de hacer que las cosas funcionen mejor.',
    'Me trato con la misma gentileza con la que trato a quienes amo.',
  ],
  Libra: [
    'Soy un tejedor/a de armonía en todo lo que toco.',
    'Mis relaciones son equilibradas, justas y hermosas.',
    'Merezco belleza y orden en mi espacio.',
    'Mi voz diplomática puede cambiar conversaciones difíciles.',
    'Soy justo/a y considerado/a con todos, incluido yo mismo/a.',
    'Tomar decisiones es una habilidad que practico con confianza.',
    'El equilibrio que busco en el mundo comienza en mi interior.',
    'Soy un/a artista de la vida. La belleza que creo importa.',
    'Tengo el don de ver el bien en todas las personas.',
    'Mis relaciones son mis mayores maestras y mis mayores tesoros.',
  ],
  Escorpio: [
    'Mi profundidad es un don extraordinario, no una carga.',
    'Confío en mi intuición para ver más allá de lo aparente.',
    'Tengo el poder de transformar el dolor en sabiduría.',
    'Soy leal, intenso/a y auténtico/a. Eso tiene mucho valor.',
    'Mi capacidad de sentir profundamente me permite conectar de verdad.',
    'No le tengo miedo a los cambios. Soy experto/a en renacer.',
    'Mis secretos son míos y tengo derecho a mi privacidad.',
    'Soy poderoso/a cuando actúo desde el amor y no desde el miedo.',
    'La transformación es mi superpoder. Puedo renacer cuando lo necesite.',
    'Tengo acceso a una sabiduría profunda que pocos poseen.',
  ],
  Sagitario: [
    'Soy un/a explorador/a del mundo y de las ideas.',
    'Mi optimismo y mi fe en la vida son contagiosos.',
    'Tengo permiso para soñar en grande, muy grande.',
    'La libertad que necesito está en mi interior.',
    'Cada experiencia es una aventura que me hace más sabio/a.',
    'Comparto lo que aprendo y eso me conecta con el mundo.',
    'Confío en que el universo tiene un plan maravilloso para mí.',
    'Soy valiente para hacer las preguntas que otros no se atreven.',
    'Mi fe en la vida me abre puertas que otros no pueden ver.',
    'Soy libre y esa libertad es mi mayor responsabilidad y mi mayor regalo.',
  ],
  Capricornio: [
    'Soy capaz de construir cualquier cosa que me proponga.',
    'Mi esfuerzo constante me lleva exactamente donde quiero llegar.',
    'Merezco descansar y celebrar mis logros con orgullo.',
    'Soy responsable y eso me da poder sobre mi vida.',
    'Cada paso pequeño me acerca a mi gran propósito.',
    'Soy disciplinado/a porque amo los resultados que mi esfuerzo crea.',
    'Mi paciencia es una fortaleza que pocos poseen.',
    'Confío en mi capacidad de superar cualquier obstáculo.',
    'Construyo el futuro con mis manos, con amor y con dedicación.',
    'Soy digno/a de todo lo que trabajo para alcanzar.',
  ],
  Acuario: [
    'Soy un innovador/a. Mi mente piensa diferente y eso es un regalo.',
    'Tengo permiso para ser completamente yo mismo/a, sin pedir disculpas.',
    'Mi originalidad hace al mundo más interesante y más justo.',
    'Pienso en el bien de todos y eso me da un propósito grande.',
    'Mis ideas pueden cambiar el mundo. Me las tomo en serio.',
    'Soy libre de ser diferente. La diferencia es mi mayor contribución.',
    'Me conecto con las personas desde la autenticidad y la igualdad.',
    'Soy parte de una generación que llegó a transformar el futuro.',
    'Mi visión del mundo es necesaria. El mundo me necesita a mí.',
    'Soy único/a y eso no es un defecto. Es exactamente lo que vine a ser.',
  ],
  Piscis: [
    'Soy sensible y eso me permite conectar con el corazón del mundo.',
    'Mi intuición es un superpoder que guía mis pasos.',
    'Soy un/a artista del alma. Lo que creo tiene magia.',
    'Merezco entornos hermosos, amorosos y en paz.',
    'Confío en los mensajes que me llegan en sueños e intuiciones.',
    'Mis emociones son un océano de sabiduría interior.',
    'Soy compasivo/a con todos, incluido yo mismo/a.',
    'Hay algo mágico en mí que el mundo necesita ver.',
    'Tengo acceso a una profundidad espiritual que me guía siempre.',
    'Soy amado/a por el universo entero, exactamente como soy.',
  ],
};

export const AFFIRMATIONS_BY_MOON: Record<string, string[]> = {
  Aries: ['Mis emociones son rápidas y válidas. Las honro sin juzgarlas.', 'Tengo el poder de actuar cuando siento que debo hacerlo.'],
  Tauro: ['Me permito sentir con calma y profundidad. No hay prisa.', 'Mi mundo interior es tan rico y estable como la tierra.'],
  Géminis: ['Tengo palabras para todo lo que siento. Mi voz emocional importa.', 'Puedo sentir muchas cosas al mismo tiempo y eso está bien.'],
  Cáncer: ['Mis emociones son mi hogar interior. Siempre puedo volver a ellas.', 'Soy amado/a profundamente, aunque no siempre lo digan con palabras.'],
  Leo: ['Merezco que mis emociones sean vistas y celebradas.', 'Mi corazón emocional es cálido, generoso y lleno de luz.'],
  Virgo: ['Me permito sentir sin tener que entender todo de inmediato.', 'Mis emociones son perfectas tal como son, sin necesidad de corregirlas.'],
  Libra: ['Mis emociones buscan equilibrio y eso es hermoso.', 'Me merezco relaciones donde mis sentimientos sean tratados con justicia.'],
  Escorpio: ['Mi profundidad emocional es un tesoro, no una carga.', 'Confío en mis emociones más profundas. Me dicen la verdad.'],
  Sagitario: ['Mis emociones son libres, expansivas y llenas de esperanza.', 'Tengo permiso para sentir alegría profunda y sin culpa.'],
  Capricornio: ['Tengo permiso para sentir sin tener que ser fuerte siempre.', 'Mi madurez emocional es un regalo que desarrollé con amor.'],
  Acuario: ['Mis emociones son únicas e interesantes, igual que todo lo mío.', 'Tengo permiso para sentir y también para necesitar espacio.'],
  Piscis: ['Mis emociones son mensajes del alma. Las escucho con amor.', 'Soy sensible y compasivo/a. Eso es una fortaleza extraordinaria.'],
};

type CompatFn = (childName: string, adjSuffix: string) => string;

export const COMPATIBILITY_TEXTS: Record<string, CompatFn> = {
  Aries: (n) => `Como niño con Sol en Aries, ${n} necesita padres que sean activos, directos y que no tengan miedo de su energía. El mayor regalo que pueden darle es libertad para actuar, espacio para liderar y la seguridad de que sus impulsos serán canalizados, no reprimidos.\n\n✦ Lo que más necesita de sus padres: Validación de su liderazgo. Cuando ${n} toma la iniciativa, aunque no salga perfecto, necesita escuchar "lo intentaste y eso vale". Límites con explicación: decirle "no" sin razón genera rebelión en Aries.\n\n✦ Cómo comunicarse mejor: Directo, breve y sin rodeos. Los Aries se desconectan de los sermones largos. Una frase contundente tiene más impacto que diez minutos de explicaciones.\n\n✦ Lo que le estresa: La pasividad, la lentitud excesiva, sentir que no puede avanzar. La sensación de estar atrapado puede generar explosiones emocionales en ${n}.\n\n✦ Lo que le sana: El movimiento físico, las aventuras, los nuevos comienzos. Después de un momento difícil, proponer una actividad nueva y activa restablece el equilibrio de ${n} más rápido que cualquier conversación.`,
  Tauro: (n) => `Como niño con Sol en Tauro, ${n} necesita padres que sean constantes, pacientes y que construyan confianza a través de la consistencia en el tiempo. La seguridad no se gana con palabras para Tauro: se gana con actos repetidos a lo largo de los años.\n\n✦ Lo que más necesita de sus padres: Rutinas estables y promesas cumplidas. Cada vez que se cumple lo prometido, el mundo de ${n} se hace un poco más seguro. Contacto físico: abrazos, caricias, presencia corporal que diga "estoy aquí".\n\n✦ Cómo comunicarse mejor: Con calma, sin prisas y dando tiempo para que procese. ${n} necesita tiempo entre la pregunta y la respuesta. Presionar genera el efecto contrario: terquedad y cierre.\n\n✦ Lo que le estresa: Los cambios repentinos, la inestabilidad, las promesas rotas. Para ${n}, que le digan que van a hacer algo y luego no suceda genera una herida profunda en la confianza.\n\n✦ Lo que le sana: El contacto con la naturaleza, la comida rica, la música, los rituales familiares que se repiten. La sensorialidad es su idioma de sanación.`,
  Géminis: (n) => `Como niño con Sol en Géminis, ${n} necesita padres que sean curiosos, comunicativos y que disfruten genuinamente de explorar el mundo junto a él. El aburrimiento es el peor escenario para un niño Géminis.\n\n✦ Lo que más necesita de sus padres: Conversaciones reales y tiempo de calidad intelectual. Leer juntos, hacer preguntas, ver documentales, debatir ideas. ${n} necesita un compañero de exploración más que un maestro con respuestas.\n\n✦ Cómo comunicarse mejor: Con variedad y creatividad. La misma conversación de siempre no funciona. Cambiar el formato mantiene abierta la comunicación con ${n}.\n\n✦ Lo que le estresa: La monotonía, las reglas sin explicación lógica, sentir que no puede preguntar lo que genuinamente le interesa.\n\n✦ Lo que le sana: El movimiento, las palabras, la estimulación mental. Cuando ${n} está inquieto emocionalmente, leer juntos o simplemente hablar mientras camina puede restablecer su equilibrio interno.`,
  Cáncer: (n) => `Como niño con Sol en Cáncer, ${n} necesita padres que sean emocionalmente presentes, que hagan del hogar un lugar verdaderamente seguro y que entiendan que su mundo interior es tan real e importante como el externo.\n\n✦ Lo que más necesita de sus padres: Presencia emocional auténtica. No basta con estar en el mismo cuarto: ${n} necesita sentir que sus emociones son recibidas y comprendidas. Los rituales de conexión son su ancla emocional.\n\n✦ Cómo comunicarse mejor: Desde la emoción, no desde la lógica. "Entiendo que estás triste" abre más puertas que "no tienes razón para estar triste". Validar primero, resolver después.\n\n✦ Lo que le estresa: Las discusiones familiares, los ambientes fríos o distantes. ${n} absorbe el clima emocional familiar como una esponja y lo lleva en el cuerpo.\n\n✦ Lo que le sana: El calor del hogar, la comida preparada con amor, el contacto físico y saber con certeza que es amado incondicionalmente.`,
  Leo: (n) => `Como niño con Sol en Leo, ${n} necesita padres que celebren su singularidad con genuino entusiasmo, que le den escenarios donde brillar y que entiendan que su necesidad de reconocimiento no es vanidad: es una necesidad del alma.\n\n✦ Lo que más necesita de sus padres: Reconocimiento auténtico y frecuente. No exagerado ni vacío, sino genuino: "vi lo que hiciste y es notable". Tiempo de calidad como protagonista: que los padres le escuchen de verdad, sin distracciones.\n\n✦ Cómo comunicarse mejor: Con entusiasmo y expresividad. Los Leos responden al calor emocional. Una conversación cálida, con contacto visual y sin el celular de por medio, abre el corazón de ${n} completamente.\n\n✦ Lo que le estresa: Sentirse invisible, ser ignorado/a, recibir críticas públicas o comparaciones con otros.\n\n✦ Lo que le sana: El juego creativo, el baile, la actuación, ser el protagonista de algo. Después de un momento difícil, proponer una actividad donde pueda brillar restablece su energía y su confianza.`,
  Virgo: (n) => `Como niño con Sol en Virgo, ${n} necesita padres que valoren su dedicación y su precisión, que le ayuden a gestionar su perfeccionismo con compasión y que entiendan que su necesidad de hacer las cosas bien viene de un lugar de genuina integridad.\n\n✦ Lo que más necesita de sus padres: Reconocimiento del esfuerzo más que del resultado. "Trabajaste muy duro en esto y se nota" tiene más valor para ${n} que un simple "quedó perfecto". Ayuda para gestionar la autocrítica.\n\n✦ Cómo comunicarse mejor: Con claridad, precisión y pasos concretos. "Necesito que hagas X antes de Y" funciona mejor que instrucciones vagas. ${n} trabaja mejor cuando sabe exactamente qué se espera de él.\n\n✦ Lo que le estresa: El desorden, la improvisación excesiva, sentir que no puede hacer algo lo suficientemente bien.\n\n✦ Lo que le sana: Las rutinas, el orden, los proyectos con resultados medibles y el reconocimiento de sus contribuciones prácticas.`,
  Libra: (n) => `Como niño con Sol en Libra, ${n} necesita padres que modelen la resolución de conflictos de manera justa y respetuosa, que creen entornos armoniosos y que valoren tanto su sensibilidad estética como su sentido profundo de la justicia.\n\n✦ Lo que más necesita de sus padres: Equidad genuina. ${n} nota inmediatamente cuando algo no es justo. Apoyo para tomar decisiones: la indecisión de Libra necesita andamiaje, no presión.\n\n✦ Cómo comunicarse mejor: Ofreciendo opciones equilibradas y tiempo para decidir. "¿Qué te parece más justo?" es una pregunta que activa lo mejor de ${n}.\n\n✦ Lo que le estresa: Las discusiones sin resolución, las situaciones injustas, tener que elegir entre cosas que ama por igual.\n\n✦ Lo que le sana: La belleza, la música, los espacios ordenados y armoniosos, las conversaciones donde todos son escuchados con respeto.`,
  Escorpio: (n) => `Como niño con Sol en Escorpio, ${n} necesita padres que sean absolutamente honestos, que respeten su profundidad y que no se asusten de la intensidad de su mundo emocional e interior.\n\n✦ Lo que más necesita de sus padres: Honestidad radical. ${n} detecta la mentira con una precisión asombrosa. La confianza construida desde la verdad es irrompible. Respeto por su privacidad: no presionar para que comparta lo que no está listo para compartir.\n\n✦ Cómo comunicarse mejor: Profundo, directo y sin suavizar la realidad artificialmente. Escorpio prefiere una verdad difícil a una mentira piadosa.\n\n✦ Lo que le estresa: La deshonestidad, la superficialidad forzada, sentir que sus emociones profundas son ignoradas o minimizadas.\n\n✦ Lo que le sana: El tiempo en privado, las conversaciones profundas cuando él las inicia, el reconocimiento de su intensidad como fortaleza.`,
  Sagitario: (n) => `Como niño con Sol en Sagitario, ${n} necesita padres que sean abiertos de mente, que expandan activamente su mundo y que entiendan que su necesidad de libertad y exploración no es rebeldía: es su naturaleza más esencial.\n\n✦ Lo que más necesita de sus padres: Espacios de libertad real dentro de un marco lo suficientemente amplio para que pueda explorar y aprender. Aventuras compartidas: viajes, nuevas experiencias, conversaciones filosóficas.\n\n✦ Cómo comunicarse mejor: Con honestidad y entusiasmo. Los Sagitario no toleran la hipocresía. Las metáforas y las historias son su lenguaje preferido.\n\n✦ Lo que le estresa: Sentirse atrapado/a, las reglas rígidas sin sentido aparente, la monotonía.\n\n✦ Lo que le sana: La naturaleza, el movimiento, las nuevas experiencias y las conversaciones sobre el sentido de la vida.`,
  Capricornio: (n) => `Como niño con Sol en Capricornio, ${n} necesita padres que reconozcan su madurez sin exigirle que crezca más rápido de lo que debe, que valoren su esfuerzo con la misma intensidad que valoran sus logros y que le enseñen que el descanso es tan sagrado como la productividad.\n\n✦ Lo que más necesita de sus padres: Reconocimiento del esfuerzo antes que del resultado. "Trabajaste muy duro" importa más que el calificativo o el premio. Permiso para ser niño: ${n} a veces carga demasiada responsabilidad; necesita que le recuerden que puede jugar sin propósito.\n\n✦ Cómo comunicarse mejor: Con claridad, respeto y metas. Los acuerdos claros generan confianza y cooperación en ${n}.\n\n✦ Lo que le estresa: El caos sin estructura, sentir que sus esfuerzos no son reconocidos, las metas poco claras.\n\n✦ Lo que le sana: Los logros completados, el reconocimiento genuino, el descanso bien merecido.`,
  Acuario: (n) => `Como niño con Sol en Acuario, ${n} necesita padres que respeten su originalidad sin intentar normalizarla, que estimulen su pensamiento crítico y que entiendan que su necesidad de ser diferente no es un problema a resolver sino una misión a acompañar.\n\n✦ Lo que más necesita de sus padres: Respeto por su singularidad. Cada vez que sus padres dicen "me gusta cómo piensas" o "esa es una perspectiva interesante", el corazón de ${n} se abre completamente. Espacio para su independencia.\n\n✦ Cómo comunicarse mejor: Con lógica, respeto y apertura al debate. Los Acuario no aceptan "porque lo digo yo" como respuesta. Una explicación razonada genera más respeto que la autoridad sin fundamento.\n\n✦ Lo que le estresa: Que le fuercen a encajar en moldes que no son para él, la hipocresía, las reglas que parecen arbitrarias.\n\n✦ Lo que le sana: El tiempo con sus amigos que comparten sus valores, los proyectos innovadores y saber que sus padres lo ven como el ser singular y valioso que es.`,
  Piscis: (n) => `Como niño con Sol en Piscis, ${n} necesita padres que sean emocionalmente gentiles, que protejan su sensibilidad sin sobreprotegerle y que entiendan que su mundo interior es tan real e importante como el mundo exterior.\n\n✦ Lo que más necesita de sus padres: Gentileza radical en el trato. ${n} absorbe los tonos emocionales directamente en su sistema nervioso. Un tono de voz cálido tiene un efecto profundo en su bienestar. Protección emocional sin encierro: aprender a navegar el mundo desde la sensibilidad.\n\n✦ Cómo comunicarse mejor: Con suavidad, imágenes y metáforas. El arte y la música pueden ser vehículos de comunicación más poderosos que las palabras directas para ${n}.\n\n✦ Lo que le estresa: Los ambientes fríos, ruidosos o agresivos; las exigencias de dureza emocional. También le afecta absorber el estrés de sus cuidadores.\n\n✦ Lo que le sana: El agua, la música, el arte, la naturaleza tranquila y la sensación de estar completamente seguro y amado tal como es.`,
};
